### ISSUE TITLE
Downloading the subtitles for the wrong season

### ISSUE THREAD

**Issue by Ivo3185** [subit/SubiT#26] opened 2015-03-29 21:28 UTC
Instead of downloading the subtitles for an episode from season 3 of a show, it's downloading the subtitles of the right episode, but from season 1.

**Comment by yosi-dediashvili** [comment] 2015-03-30 16:41
Could you be more specific? Which series was it?

**Comment by Ivo3185** [comment] 2015-03-30 16:46
True BloodOn seg, Mar 30, 2015 at 5:41 PM,  subit/SubiT <reply@reply.github.com> wrote:            Could you be more specific? Which series was it?

**Comment by yosi-dediashvili** [comment] 2015-04-03 09:33
What was the name of the file? 

Plus, can you look at the logs and specify from which provider the subtitle is being downloaded?

**Comment by Ivo3185** [comment] 2015-04-03 23:04
Sorry, I forgot about this and deleted the file.
I tried this with another TV show and I had the same problem.

The file's name is Fortitude.S01E01.Episode.1.WEBDL-1080p.mkv.
It uses www.Addic7ed.com and downloads S01E06 instead.

Could you could add a log.txt or add a way to copy the whole log?

**Comment by yosi-dediashvili** [comment] 2015-04-05 19:41
Hmm, the problem is already being fixed under SubiT 3.0.0 (the whole redesign of the Titles recognition will take care of that).

So, currently, we'll treat that as fixed in the next version.

**Closed by yosi-dediashvili** 2015-04-05 19:41 UTC
